In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
# Load the sheet
df = pd.read_excel("files.xlsx", sheet_name=3)

# Print column names to see what they are
print("Column names:", df.columns.tolist())

# Assuming the first column contains names and the second column contains costs
# Use actual column names instead of integer indices
name_column = df.columns[0]  # First column name
cost_column = df.columns[1]  # Second column name

# Clean the cost column
df[cost_column] = df[cost_column].astype(str).str.replace(",", "").astype(int)

# Extract variables
names = df[name_column].tolist()
ref_cost = df[cost_column].tolist()

# Print to verify
print("Mineral Names:\n", names)
print("\nRefining Costs:\n", ref_cost)


Column names: ['Unnamed: 0', 'Refining Cost (USD/Ton)']
Mineral Names:
 ['Lithium', 'Nickel', 'Cobalt', 'Graphite', 'Manganese', 'Copper', 'RareEarth', 'Zinc', 'Tin', 'Aluminum', 'Iron', 'Lead', 'Silver', 'Gold', 'Platinum', 'Phosphorus', 'Potash', 'Silicon', 'Germanium', 'Gallium', 'Antimony', 'Molybdenum', 'Vanadium', 'Tungsten', 'Selenium', 'Indium', 'Tellurium', 'Bismuth', 'Cadmium', 'Chromium']

Refining Costs:
 [5114, 3409, 16717, 4000, 3500, 4200, 191508, 2500, 2500, 2000, 700, 1000, 25000, 60000, 70000, 1300, 350, 1200, 50000, 40000, 5000, 4000, 11000, 13000, 27000, 40000, 35000, 3000, 6000, 2500]


# Assistant
The error occurs because you're trying to access columns using integer indices (df[0], df[1]), but pandas DataFrame columns are typically accessed by column names, not integer positions.

Would you like me to provide the corrected code?

In [17]:
df1 = pd.read_excel("files.xlsx", sheet_name=2)

# Print column names to see what they are
print("Column names:", df1.columns.tolist())

# Get the column names
supply_col = df1.columns[2] 
demand_col = df1.columns[3]  
price_col = df1.columns[4]
growth_rate_col = df1.columns[5]

# Create lists from the column data
supply_list = df1[supply_col].tolist()
demand_list = df1[demand_col].tolist()
price_list = df1[price_col].tolist()
growth_rate_list = df1[growth_rate_col].tolist()

# Print the lists to verify
# print(f"\n{supply_col} list:")
# print(supply_list)

# print(f"\n{demand_col} list:")
# print(demand_list)

# print(f"\n{price_col} list:")
# print(price_list)

# print(f"\n{growth_rate_col} list:")
# print(growth_rate_list)


Column names: ['Mineral', 'Year', "Supply ('000 Tonnes)", "Demand ('000 Tonnes)", 'Price_USD_per_ton', 'Growth rate']


In [50]:
# supply_list, demand_list, price_list, growth_rate_list
diff = [demand_list[i] - supply_list[i] for i in range(len(demand_list))]
# Get indices of 4 highest differences
ind = sorted(range(len(diff)), key=lambda i: diff[i], reverse=True)[:4]
print("Indices of 4 highest diffences of demand and supply: ", ind)

Indices of 4 highest diffences of demand and supply:  [17, 16, 8, 7]


# User
we need to consider rows 3*i, i = 0,1....30. Or if you know sheet's data, i have to consider data of year 2030 only for all 30 metals.

In [51]:
# only for year 2030 (5 years)
# 1. valid rows for year 2030 → rows = 0, 3, 6, 9, ...
year2030_rows = list(range(0, len(demand_list), 3))

# 2. compute diff only for those rows
diffs_2030 = {i: demand_list[i] - supply_list[i] for i in year2030_rows}

# 3. pick top 4 rows based on difference
ind = sorted(diffs_2030.keys(), key=lambda i: diffs_2030[i], reverse=True)[:4]
# Divide each element in the list by 3 instead of dividing the whole list
ind = [i//3 for i in ind]  # Using integer division to convert indices

print("Rows for year 2030 with highest differences:", ind)
print(f"Differences: {[f'{diffs_2030[i]:.3f}' for i in sorted(diffs_2030.keys(), key=lambda i: diffs_2030[i], reverse=True)[:4]]}")

Rows for year 2030 with highest differences: [0, 5, 2, 6]
Differences: ['4.706', '4.370', '3.896', '0.902']


In [65]:
# Load sheet 1
file_path = "files.xlsx"  # replace with your Excel file path
df1 = pd.read_excel(file_path, sheet_name=0)

# Skip first 2 empty rows
df1 = df1.iloc[2:].reset_index(drop=True)

# Assume top 4 mineral indices are already selected
ind = [0, 5, 2, 6]  # example indices

# Columns in sheet 1 corresponding to these minerals
cols = [i + 2 for i in ind]  # +2 to account for first 2 empty columns

# Build m as 20x4 numeric array
m = df1.iloc[:20, cols].to_numpy(dtype=float)

# Check the result
print("m matrix (20x4):")
print(m)

m matrix (20x4):
[[1.78       3.06468749 2.31150641 0.45762735]
 [1.96       1.96417848 1.35716855 0.30629076]
 [2.79       3.44124393 2.32270312 0.09234264]
 [2.92       4.74174478 1.5324127  0.41259544]
 [3.87       3.93884225 2.15259509 0.31475474]
 [4.95968319 4.29910168 2.1735615  0.21806428]
 [5.6        2.95588513 2.01657758 0.31206094]
 [6.69       4.49575057 1.61753498 0.40401558]
 [5.12899169 2.62190263 2.0145332  0.16746676]
 [2.01144663 4.48203322 1.53446769 0.20347789]
 [1.74039315 2.80141096 1.83483397 0.32043207]
 [1.80170693 5.78994672 2.05074565 0.27024661]
 [4.39326052 3.0415294  1.7964785  0.41925317]
 [2.19826585 2.21608811 1.63576887 0.32077905]
 [1.64600256 3.7709859  1.71254013 0.24615653]
 [1.78771912 4.16561333 2.42600642 0.18518562]
 [1.28482961 1.55442675 2.02062607 0.31708384]
 [4.43190207 2.62973015 1.72125105 0.16401597]
 [1.96374595 3.19577545 2.27043769 0.20363523]
 [1.61461278 4.75722146 2.01641532 0.15048932]]


In [66]:
# ------------------------------
# Year index for 2030
# ------------------------------
year_index = 0  # 0 → 2030, 1 → 2035, 2 → 2040

# ------------------------------
# Compute mass_of_ore_needed
# ------------------------------
mass_of_ore_needed = []

for i in range(20):  # depths 0 to 19
    values = []
    for j_idx, j in enumerate(ind):  # j_idx = 0..3, j = mineral index from ind
        val = (100 / m[i, j_idx]) * supply_list[3*j + year_index]
        values.append(val)
    mass_of_ore_needed.append(max(values))

# ------------------------------
# Print results
# ------------------------------
print("Optimal mass of ore needed for each depth (2030):")
for i, mass in enumerate(mass_of_ore_needed):
    print(f"Depth {i}: {mass:.3f}")


Optimal mass of ore needed for each depth (2030):
Depth 0: 1895.139
Depth 1: 2956.965
Depth 2: 1970.603
Depth 3: 1224.867
Depth 4: 1474.547
Depth 5: 1350.982
Depth 6: 1964.896
Depth 7: 1291.888
Depth 8: 2215.188
Depth 9: 1295.842
Depth 10: 2073.244
Depth 11: 1003.119
Depth 12: 1909.568
Depth 13: 2620.838
Depth 14: 1540.183
Depth 15: 1394.274
Depth 16: 3736.431
Depth 17: 2208.595
Depth 18: 1817.402
Depth 19: 1220.882
